/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smpfinal;

/**
 *
 * @author Ramon
 */
public class VentanaDialogoAbout extends javax.swing.JDialog {

    /**
     * Creacion de la Ventana Dialogo "Sobre el programa", donde muestros
     * alguna informacion sobre mi.
     */
    public VentanaDialogoAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbajo = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JButton();
        panelArriba = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelTexto = new javax.swing.JPanel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        panelImagen = new javax.swing.JPanel();
        textoImagenIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        panelAbajo.add(botonCerrar);

        getContentPane().add(panelAbajo, java.awt.BorderLayout.CENTER);

        panelArriba.setLayout(new java.awt.BorderLayout());

        panelSuperior.setLayout(new java.awt.BorderLayout());

        panelTexto.setLayout(new java.awt.GridLayout(0, 1));

        texto1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        texto1.setText("PaintCompleto - SMPFINAL - 17/18 - Versión 1.0");
        panelTexto.add(texto1);

        texto2.setText("Práctica Final realizada para la asignatura Sistemas Multimedia");
        panelTexto.add(texto2);

        jLabel1.setText("Escuela Técnica Superior de Informatica y Telecomunicaciones - Universidad de Granada   ");
        panelTexto.add(jLabel1);

        texto3.setText("© 2018, Ramón Sánchez García, Todos los derechos reservados   ");
        panelTexto.add(texto3);

        texto4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        texto4.setText("He empleado muchas horas y esfuerzo en esta aplicación, por favor, no la uses sin mi permiso :(   ");
        panelTexto.add(texto4);

        texto5.setText("Contacto: chentaco@correo.ugr.es");
        panelTexto.add(texto5);

        panelSuperior.add(panelTexto, java.awt.BorderLayout.LINE_END);

        panelImagen.setLayout(new java.awt.BorderLayout());

        textoImagenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Yazawa_Nico.png"))); // NOI18N
        panelImagen.add(textoImagenIcon, java.awt.BorderLayout.CENTER);

        panelSuperior.add(panelImagen, java.awt.BorderLayout.LINE_START);

        panelArriba.add(panelSuperior, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelArriba, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelAbajo;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTexto;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel textoImagenIcon;
    // End of variables declaration//GEN-END:variables
}
